site_name: "Red Hat Developer Hub"
site_description: RHDH Local
site_author: user:user
docs_dir: docs
plugins:
  - techdocs-core
nav:
  - "Welcome": index.md
  - "Benefits": features.md
  - "Features":
    - "Software Catalog": catalogs.md
    - "Templates": templates.md
    - "TechDocs": techdocs.md
  - "Tips & Tricks":
    - "Top 10 Tips For Better Templates": ten_template_tips.md
    - "Making Your TechDocs More Appealing": extensions.md
  - "Comparison with CNCF Backstage": comparison.md
  - "Help & Resources": help.md